outputs:
    IFTTT:
        api_key: YOUR MAKER API KEY HERE GET IT AT https://ifttt.com/maker

quick_buttons:
    da1990decade: arcade_on

buttons:
    1234deadbeef:
        output: IFTTT
        action: dash_dixie_goodnight_1
        data:
            - 'Lullaby'
            - 'OK Go'
    adefacedcafe:
        output: IFTTT
        action: arcade_off

# If you don't see your buttons, try turning this on
# It will show all devices asking for ID on the network,
# whether they look Amazon-y or not
show_all_devices: true
